- name: Ensure that the hosts have Git installed
  hosts: all
  remote_user: root
  tasks: 
    - name: Install the latest version of Git
      ansible.builtin.package:
        name: git
        state: latest