- name: Ensure that the hosts have Python installed
  hosts: all
  remote_user: root
  tasks: 
    - name: Install the latest version of python3
      ansible.builtin.package:
        name: python3
        state: latest
    - name: Install the latest version of python3-venv
      ansible.builtin.package:
        name: python3-venv
        state: latest