- name: Ensure all active hosts have the latest program version from the Git Repository
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Clone/pull the project master branch
      ansible.builtin.git:
        repo: 'https://github.com/2105-may24-devops/jacob-project0.git'
        dest: /home/jacob/jacob-project0/
        single_branch: yes
        version: master
    - name: Create venv directory
      ansible.builtin.file:
        path: /home/jacob/jacob-project0/venv
        state: directory
    - name: Ensure pip is installed on hosts
      ansible.builtin.package:
        name: python-setuptools
        state: latest
    - name: Create virtual environment using pip
      ansible.builtin.pip:
        requirements: /home/jacob/jacob-project0/requirements.txt
        virtualenv: /home/jacob/jacob-project0/venv/
        virtualenv_command: '-m venv'
        virtualenv_python: python3.9
        state: latest




