- name: Load Docker and the project container
  hosts: revature
  gather_facts: false
  tasks:
    - name: Fetch latest Docker installation script
      ansible.builtin.get_url:
        url: https://get.docker.com/
        dest: ~/jacob-project0/get_docker.sh
    - name: Install Docker if it does not exist on the host
      ansible.builtin.command: 
        cmd: bash get_docker.sh
        creates: /usr/bin/docker