- name: Ensure all hosts have the latest program version from the Git Repository
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Clone/pull the project master branch
      ansible.builtin.git:
        repo: 'https://github.com/2105-may24-devops/jacob-project0.git'
        dest: ~/jacob-project0/
        single_branch: yes
        version: master
    - name: Create venv directory
      ansible.builtin.file:
        path: ~/jacob-project0/venv
        state: directory
    - name: Create venv environment
      ansible.builtin.shell: 'python3 -m venv ~/jacob-project0/venv/'




