- name: Run Function Tests on AssetManagement.py
  hosts: all
  gather_facts: false
  tasks: 
    - name: run system tests - write, copy, append
      ansible.builtin.assert:
        that: "{{ item }}"
        fail_msg: "{{ item }} found unexpected output"
        success_msg: "{{ item }} ran as expected"
      with_items:
        - 'write_test.sh'
        - 'copy_test.sh'
        - 'append_test.sh'
     