- name: Ensure the git repository of the program is removed from all hosts
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Remove project folder from project
      ansible.builtin.file:
        path: /home/jacob/jacob-project0/
        state: absent