- name: Ensure the git repository of the program is removed from all hosts
  hosts: all
  remote_user: root
  tasks:
    - name: Remove project folder from project
      ansible.builtin.file:
        path: ~/jacob-project0
        state: absent